-- Raw/Landing layer.
-- Source data is preserved as received; parsing is intentionally deferred.
-- Run in a Snowflake database/schema of your choice.

CREATE OR REPLACE TABLE RAW_MEMBER_FEED (
    BATCH_ID            VARCHAR(100) NOT NULL,
    SOURCE_FILE_NAME    VARCHAR(500) NOT NULL,
    RECORD_TYPE         VARCHAR(1),
    RAW_RECORD          VARCHAR,
    INGESTED_AT         TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW_REDEMPTION_FEED (
    BATCH_ID            VARCHAR(100) NOT NULL,
    SOURCE_FILE_NAME    VARCHAR(500) NOT NULL,
    RAW_PAYLOAD         VARIANT NOT NULL,
    INGESTED_AT         TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE ETL_BATCH_AUDIT (
    BATCH_ID             VARCHAR(100) NOT NULL,
    SOURCE_FILE_NAME     VARCHAR(500),
    SOURCE_RECORD_COUNT  NUMBER,
    VALID_RECORD_COUNT   NUMBER,
    INVALID_RECORD_COUNT NUMBER,
    STARTED_AT           TIMESTAMP_NTZ,
    COMPLETED_AT         TIMESTAMP_NTZ,
    STATUS               VARCHAR(30),
    ERROR_MESSAGE        VARCHAR
);
