-- Country-specific targets.
-- In production, these can be physical tables or dynamic tables/views
-- depending on the downstream contract. This assessment uses tables.

CREATE OR REPLACE TABLE TABLE_INDIA LIKE DIM_MEMBER_CURRENT;
CREATE OR REPLACE TABLE TABLE_USA   LIKE DIM_MEMBER_CURRENT;
CREATE OR REPLACE TABLE TABLE_AUS   LIKE DIM_MEMBER_CURRENT;
CREATE OR REPLACE TABLE TABLE_OTHER LIKE DIM_MEMBER_CURRENT;

-- The load is replace-from-current-state, not append-only. This is important:
-- if member 223457 moves from USA to IND, the member must disappear from USA.

TRUNCATE TABLE TABLE_INDIA;
TRUNCATE TABLE TABLE_USA;
TRUNCATE TABLE TABLE_AUS;
TRUNCATE TABLE TABLE_OTHER;

INSERT INTO TABLE_INDIA
SELECT * FROM DIM_MEMBER_CURRENT WHERE UPPER(COUNTRY_CODE) IN ('IND', 'INDIA');

INSERT INTO TABLE_USA
SELECT * FROM DIM_MEMBER_CURRENT WHERE UPPER(COUNTRY_CODE) IN ('USA', 'US');

INSERT INTO TABLE_AUS
SELECT * FROM DIM_MEMBER_CURRENT WHERE UPPER(COUNTRY_CODE) IN ('AUS', 'AU', 'AUSTRALIA');

INSERT INTO TABLE_OTHER
SELECT * FROM DIM_MEMBER_CURRENT
WHERE UPPER(COUNTRY_CODE) NOT IN (
    'IND', 'INDIA', 'USA', 'US', 'AUS', 'AU', 'AUSTRALIA'
)
OR COUNTRY_CODE IS NULL;
