-- Persisted data-quality framework.

CREATE OR REPLACE TABLE DATA_QUALITY_RESULTS (
    BATCH_ID       VARCHAR(100) NOT NULL,
    CHECK_NAME     VARCHAR(200) NOT NULL,
    SEVERITY       VARCHAR(20) NOT NULL,
    RECORD_KEY     VARCHAR(255),
    ERROR_MESSAGE  VARCHAR,
    DETECTED_AT    TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP()
);

-- Mandatory member fields.
INSERT INTO DATA_QUALITY_RESULTS (BATCH_ID, CHECK_NAME, SEVERITY, RECORD_KEY, ERROR_MESSAGE)
SELECT BATCH_ID, 'MANDATORY_MEMBER_FIELDS', 'ERROR', COALESCE(MEMBER_ID, MEMBER_NAME),
       'Member_Name, Member_ID, and Enrollment_Date are mandatory'
FROM STG_MEMBER
WHERE MEMBER_NAME IS NULL OR MEMBER_ID IS NULL OR ENROLLMENT_DATE IS NULL;

-- Business identity uniqueness inside a batch.
INSERT INTO DATA_QUALITY_RESULTS (BATCH_ID, CHECK_NAME, SEVERITY, RECORD_KEY, ERROR_MESSAGE)
SELECT BATCH_ID, 'MEMBER_ID_UNIQUENESS', 'ERROR', MEMBER_ID,
       'Duplicate Member_ID within batch; latest record wins only at current-state layer'
FROM STG_MEMBER
GROUP BY BATCH_ID, MEMBER_ID
HAVING MEMBER_ID IS NOT NULL AND COUNT(*) > 1;

-- Tier domain.
INSERT INTO DATA_QUALITY_RESULTS (BATCH_ID, CHECK_NAME, SEVERITY, RECORD_KEY, ERROR_MESSAGE)
SELECT BATCH_ID, 'TIER_CODE_DOMAIN', 'ERROR', MEMBER_ID,
       'Tier_Code must be PLT, GLD, or SLV when populated'
FROM STG_MEMBER
WHERE TIER_CODE IS NOT NULL
  AND UPPER(TIER_CODE) NOT IN ('PLT', 'GLD', 'SLV');

-- Active flag domain.
INSERT INTO DATA_QUALITY_RESULTS (BATCH_ID, CHECK_NAME, SEVERITY, RECORD_KEY, ERROR_MESSAGE)
SELECT BATCH_ID, 'ACTIVE_MEMBER_DOMAIN', 'ERROR', MEMBER_ID,
       'Active Member must be A or I when populated'
FROM STG_MEMBER
WHERE ACTIVE_MEMBER IS NOT NULL
  AND UPPER(ACTIVE_MEMBER) NOT IN ('A', 'I');

-- Date consistency.
INSERT INTO DATA_QUALITY_RESULTS (BATCH_ID, CHECK_NAME, SEVERITY, RECORD_KEY, ERROR_MESSAGE)
SELECT BATCH_ID, 'DATE_CONSISTENCY', 'ERROR', MEMBER_ID,
       'Enrollment date cannot be after last flight date'
FROM STG_MEMBER
WHERE ENROLLMENT_DATE IS NOT NULL
  AND LAST_FLIGHT_DATE IS NOT NULL
  AND ENROLLMENT_DATE > LAST_FLIGHT_DATE;

-- Future DOB.
INSERT INTO DATA_QUALITY_RESULTS (BATCH_ID, CHECK_NAME, SEVERITY, RECORD_KEY, ERROR_MESSAGE)
SELECT BATCH_ID, 'DOB_NOT_IN_FUTURE', 'ERROR', MEMBER_ID,
       'Date of birth cannot be in the future'
FROM STG_MEMBER
WHERE DATE_OF_BIRTH > CURRENT_DATE();

-- DOB is optional in the source specification, so NULL DOB is a warning.
INSERT INTO DATA_QUALITY_RESULTS (BATCH_ID, CHECK_NAME, SEVERITY, RECORD_KEY, ERROR_MESSAGE)
SELECT BATCH_ID, 'OPTIONAL_DOB_MISSING', 'WARNING', MEMBER_ID,
       'Date of birth is missing'
FROM STG_MEMBER
WHERE DATE_OF_BIRTH IS NULL;

-- Country normalization check.
INSERT INTO DATA_QUALITY_RESULTS (BATCH_ID, CHECK_NAME, SEVERITY, RECORD_KEY, ERROR_MESSAGE)
SELECT BATCH_ID, 'COUNTRY_CODE_MISSING', 'WARNING', MEMBER_ID,
       'Country is missing; record will route to TABLE_OTHER'
FROM STG_MEMBER
WHERE COUNTRY_CODE IS NULL;

-- Redemption checks.
INSERT INTO DATA_QUALITY_RESULTS (BATCH_ID, CHECK_NAME, SEVERITY, RECORD_KEY, ERROR_MESSAGE)
SELECT BATCH_ID, 'REDEMPTION_REQUIRED_FIELDS', 'ERROR', COALESCE(TXN_ID, MEMBER_ID),
       'Redemption requires member_id, txn_id, txn_date, and feed_date'
FROM FACT_REDEMPTION
WHERE MEMBER_ID IS NULL OR TXN_ID IS NULL OR TXN_DATE IS NULL OR FEED_DATE IS NULL;

INSERT INTO DATA_QUALITY_RESULTS (BATCH_ID, CHECK_NAME, SEVERITY, RECORD_KEY, ERROR_MESSAGE)
SELECT BATCH_ID, 'REDEMPTION_MILES_POSITIVE', 'ERROR', TXN_ID,
       'Miles redeemed must be greater than zero'
FROM FACT_REDEMPTION
WHERE MILES_REDEEMED IS NULL OR MILES_REDEEMED <= 0;

INSERT INTO DATA_QUALITY_RESULTS (BATCH_ID, CHECK_NAME, SEVERITY, RECORD_KEY, ERROR_MESSAGE)
SELECT BATCH_ID, 'TXN_DATE_NOT_AFTER_FEED_DATE', 'ERROR', TXN_ID,
       'Transaction date cannot be after feed date'
FROM FACT_REDEMPTION
WHERE TXN_DATE > FEED_DATE;

INSERT INTO DATA_QUALITY_RESULTS (BATCH_ID, CHECK_NAME, SEVERITY, RECORD_KEY, ERROR_MESSAGE)
SELECT BATCH_ID, 'TXN_ID_UNIQUENESS', 'ERROR', TXN_ID,
       'Transaction ID occurs more than once in the same batch'
FROM FACT_REDEMPTION
GROUP BY BATCH_ID, TXN_ID
HAVING TXN_ID IS NOT NULL AND COUNT(*) > 1;
